# Compose file build variables set in .env
services:
  supervisor:
    build:
      context: ./build
      args:
        # Remove as appropriate
        IMAGE_BASE: ${IMAGE_BASE:-nvidia/cuda:12.9.1-base-ubuntu22.04}
        IMAGE_TAG: ${IMAGE_TAG:-v1-redo}
        XPU_TARGET: ${XPU_TARGET:-NVIDIA_GPU}
        CUDA_STRING: ${CUDA_STRING:-12.9.1-base}
        ROCM_STRING: ${ROCM_STRING:-5.7-runtime}
      tags:
        - "ghcr.io/gitgud5000/base-image:${IMAGE_TAG:-v1-redo}"
        
    image: ghcr.io/gitgud5000/base-image:${IMAGE_TAG:-v1-redo}
    
    ## For Nvidia GPU's - Enabled for RTX 5090
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    
    
    devices:
      - "/dev/dri:/dev/dri"
      # For AMD GPU
      #- "/dev/kfd:/dev/kfd"
      
    volumes:
      # Workspace
      - ./workspace:${WORKSPACE:-/workspace}:rshared
      # Will echo to root-owned authorized_keys file;
      # Avoids changing local file owner
      - ./config/authorized_keys:/root/.ssh/authorized_keys_mount
      - ./config/provisioning/default.sh:/opt/ai-dock/bin/provisioning.sh
      # TLS Certificates
      - ./config/tls/container.crt:/opt/caddy/tls/container.crt
      - ./config/tls/container.key:/opt/caddy/tls/container.key
      
    ports:
        # SSH available on host machine port 2222 to avoid conflict. Change to suit
        - ${SSH_PORT_HOST:-2222}:22
        # Syncthing
        - ${SYNCTHING_UI_PORT_HOST:-8384}:${SYNCTHING_UI_PORT_HOST:-8384}
        - ${SYNCTHING_TRANSPORT_PORT_HOST:-22999}:${SYNCTHING_TRANSPORT_PORT_HOST:-22999}
        # Caddy port for service portal
        - ${SERVICEPORTAL_PORT_HOST:-1111}:${SERVICEPORTAL_PORT_HOST:-1111}

    environment:
        # Important: Edit values in .env - not here.
        # Don't enclose values in quotes
        - DIRECT_ADDRESS=${DIRECT_ADDRESS:-127.0.0.1}
        - DIRECT_ADDRESS_GET_WAN=${DIRECT_ADDRESS_GET_WAN:-false}
        - WORKSPACE=${WORKSPACE:-/workspace}
        - WORKSPACE_SYNC=${WORKSPACE_SYNC:-false}
        - CADDY_AUTH_COOKIE_NAME=${CADDY_AUTH_COOKIE_NAME:-}
        - CF_TUNNEL_TOKEN=${CF_TUNNEL_TOKEN:-}
        - CF_QUICK_TUNNELS=${CF_QUICK_TUNNELS:-true}
        - WEB_ENABLE_AUTH=${WEB_ENABLE_AUTH:-true}
        - WEB_ENABLE_HTTPS=${WEB_ENABLE_HTTPS:-false}
        - WEB_USER=${WEB_USER:-user}
        - WEB_PASSWORD=${WEB_PASSWORD:-password}
        - SERVERLESS=${SERVERLESS:-false}
        - SYNCTHING_UI_PORT_HOST=${SYNCTHING_UI_PORT_HOST:-8384}
        - SYNCTHING_URL=${SYNCTHING_URL:-}
        - SYNCTHING_TRANSPORT_PORT_HOST=${SYNCTHING_TRANSPORT_PORT_HOST:-22999}
        - SSH_PORT_HOST=${SSH_PORT_HOST:-2222}
        - SERVICEPORTAL_PORT_HOST=${SERVICEPORTAL_PORT_HOST:-1111}
        - SERVICEPORTAL_METRICS_PORT=${SERVICEPORTAL_METRICS_PORT:-21111}
        - SERVICEPORTAL_URL=${SERVICEPORTAL_URL:-}
        #- PROVISIONING_SCRIPT=https://raw.githubusercontent.com/ai-dock/base-image/main/config/provisioning/default.sh
